name: Test Workflow

on:
  push:
    branches:
      - main

jobs:
  run-tests:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14'

      - name: Install dependencies
        run: npm install

      - name: Run Unit tests
        id: unit-tests
        run: npm test

      - name: Publish HTML files
        if: ${{ always() }}
        uses: actions/upload-artifact@v2
        with:
          name: html-artifact
          path: "*.html"
          
      - name: Generate Dynamic Content
        run: |
          echo "GitHub Run ID: ${{ github.run_id }}" > dynamic_content.txt

      - name: Update README with Dynamic Content
        run: |
          sed -i 's|<INSERT_DYNAMIC_CONTENT_HERE>|'"$(cat dynamic_content.txt)"'|' README.md

      - name: Commit and Push Changes
        run: |
            git config user.name "Your Name"
            git config user.email "your.email@example.com"
            git remote set-url origin "https://$GITHUB_ACTOR:${{ secrets.YOUR_PAT_SECRET }}@github.com/${{ github.repository }}.git"
            git add README.md
            git commit -m "Update README with dynamic content"
            git push
        env:
            GITHUB_ACTOR: ${{ github.actor }}
